<a href="https://colab.research.google.com/github/vp19627/CE888/blob/master/Lab_1/Lab_1_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np
print('Question 1') 
a = np.array([[0,1],[2,3],[4,5],[6,7]])
print("4x2 integer array and attributes printed:",a)

print('Question 2')

b= np.array([1, 2, 7, 5,4,6,3,9,8,10])
print("Array of dimension-(1,10): ",b)
b_a=np.sort(b)
b_d=np.sort(b)[::-1]

print('Sorted Array in ascending Order: ', b_a)
print('Sorted Array in Descending Order: ', b_d)
print('Question 3')
x=np.array([1,2,3,4,5,6,7,8,9])
y=np.reshape(x, (-1,3))
print("1D  array is:",x)
print("2D array is:",y) 
print('Question 4')
x4=np.array([[0,1],[2,3],[4,5],[6,7]])
y4=np.array([[8,9],[10,11],[12,13]])
print("First array:",x4)
print("Second array:",y4)
print("Stack arrays vertically", np.concatenate((x4, y4), axis=0))
print("Stack arrays horizontally:", np.concatenate((x4, y4), axis=None))

print('Question 5')
x5=np.array([[0,1],[2,3],[4,5],[6,7]])
y5=np.array([[8,9],[10,11],[6,13],[14,7]])
print("Common values between two arrays:")
print(np.intersect1d(x5, y5))

print('Question 6')
x4=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print("Array for this question is:",x4)
maxElement_col = np.amax(x4,axis=0 )
maxElement_row = np.amax(x4,axis=1 )
print("Max value of each column is:",maxElement_col)
print("Max value of each row is:",maxElement_row)
minElement_col = np.amin(x4,axis=0 )
minElement_row = np.amin(x4,axis=1 )
print("Min value of each column is:",minElement_col)
print("Min value of each row is:",minElement_row)

print('Question 7')
x7=np.random.rand(1,100)
print("Random arrat of size 100: ",x7)
print("Mean value:",np.mean(x7))
print("Median value:",np.median(x7))
print("Standard deviation",np.std(x7))

print('Question 8')

x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

print("Question 9")
x9=np.random.rand(4,4,3)
print("(4,4,3)-array:",x9)
y9=np.random.rand(4,4)
print("(4,4)-array",y9)
m=np.dot(y9,x9)
print("Multiplication=",m)


Question 1
4x2 integer array and attributes printed: [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Question 2
Array of dimension-(1,10):  [ 1  2  7  5  4  6  3  9  8 10]
Sorted Array in ascending Order:  [ 1  2  3  4  5  6  7  8  9 10]
Sorted Array in Descending Order:  [10  9  8  7  6  5  4  3  2  1]
Question 3
1D  array is: [1 2 3 4 5 6 7 8 9]
2D array is: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Question 4
First array: [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Second array: [[ 8  9]
 [10 11]
 [12 13]]
Stack arrays vertically [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
Stack arrays horizontally: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
Question 5
Common values between two arrays:
[6 7]
Question 6
Array for this question is: [[0 1 2 3 4]
 [5 6 7 8 9]]
Max value of each column is: [5 6 7 8 9]
Max value of each row is: [4 9]
Min value of each column is: [0 1 2 3 4]
Min value of each row is: [0 5]
Question 7
Random arrat of size 100:  [[0.07539916 0.30251233 0.81748014 0.41258343 0.87245897 0.52746595
  0.8