<a href="https://colab.research.google.com/github/vp19627/CE888/blob/master/Lab5/Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

# Assign spreadsheet filename: file
file = 'https://github.com/vp19627/CE888/blob/master/jester-data-1.xls?raw=true'

# Load spreadsheet: xl
xl = pd.ExcelFile(file)

# Load a sheet into a DataFrame by name: df1
df1 = xl.parse(0)



df1.drop(df1.columns[[0]], axis = 1, inplace = True) 

df1.head(5)

-7.82   8.79  -9.66  -8.16  -7.52  ...  99.22  -5.63  99.23  99.24  99.25
0   4.08  -0.29   6.36   4.37  -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
1  99.00  99.00  99.00  99.00   9.03  ...  99.00  99.00  99.00  99.00  99.00
2  99.00   8.35  99.00  99.00   1.80  ...  99.00  99.00  99.00  99.00  99.00
3   8.50   4.61  -4.17  -5.39   1.36  ...   1.55   3.11   6.55   1.80   1.60
4  -6.17  -3.54   0.44  -8.50  -7.09  ...  -3.35   0.05  -9.08  -5.05  -3.45

[5 rows x 100 columns]

In [4]:
print(df1.shape)

(24982, 100)


In [5]:
df1.describe()

-7.82          8.79  ...         99.24         99.25
count  24982.000000  24982.000000  ...  24982.000000  24982.000000
mean      34.403125     27.094822  ...     55.751626     60.136534
std       46.707230     44.228739  ...     49.237364     47.913859
min       -9.950000     -9.950000  ...     -9.950000     -9.950000
25%       -0.150000     -2.180000  ...      1.322500      3.930000
50%        5.050000      3.690000  ...     99.000000     99.000000
75%       99.000000     99.000000  ...     99.000000     99.000000
max       99.000000     99.000000  ...     99.000000     99.000000

[8 rows x 100 columns]

In [6]:
arr = df1.values
print(arr.shape)
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

(24982, 100)
1810381 (1810381,)


In [7]:
print(arr)
print(np.where(arr!=99))

[[ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.    8.35 99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]
(array([    0,     0,     0, ..., 24981, 24981, 24981]), array([ 0,  1,  2, ..., 69, 70, 86]))


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [10]:
arr[idx[0][0], idx[1][0]]

8.59

In [11]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:

import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [13]:
df1.shape[0]

24982

In [0]:

n_latent_factors = 2

user_ratings = df1.values
# Initialise as random values
latent_user_preferences = np.random.random((df1.shape[0], n_latent_factors))
latent_item_features = np.random.random((df1.shape[1], n_latent_factors))

In [15]:
latent_item_features.shape[0]

100

In [16]:
latent_user_preferences

array([[0.522, 0.263],
       [0.376, 0.721],
       [0.256, 0.123],
       ...,
       [0.891, 0.456],
       [0.1  , 0.164],
       [0.395, 0.703]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
  prediction_rating = predict_rating(user_id, item_id)
  err =  prediction_rating - rating
  user_pref_values = latent_user_preferences[user_id][:]
  latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
  latent_item_features[item_id] -= alpha * err * user_pref_values
  return err
    

def sgd(iterations=300000):
  for iteration in range(iterations):
    error=[]
    for user_id in range(latent_user_preferences.shape[0]):
      for item_id in range(latent_item_features.shape[0]):
        rating = user_ratings[user_id][item_id]
        if not np.isnan(rating):
          err = train(user_id, item_id, rating)
          error.append(err)
          mse = (np.array(error) ** 2).mean()
          if (iteration % 10000) == 0:
            print(mse)

In [20]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[0.925, 0.822, 0.989, ..., 2.4  , 1.9  , 2.172],
       [3.677, 2.546, 3.614, ..., 8.592, 6.877, 7.76 ],
       [2.785, 2.124, 2.823, ..., 6.765, 5.392, 6.116],
       ...,
       [1.449, 1.301, 1.555, ..., 3.778, 2.99 , 3.42 ],
       [0.322, 0.205, 0.309, ..., 0.729, 0.586, 0.658],
       [1.348, 0.838, 1.283, ..., 3.025, 2.433, 2.73 ]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df1.columns

In [22]:
#Best joke
df_mean=[]
df_mean.append(df1.mean(axis = 0, skipna = True))

type(df_mean)
df_mean[-1].sort_values(ascending=False).head(1)

99.1    65.510407
dtype: float64

In [23]:
#worst joke
df_mean=df1.mean(axis = 0, skipna = True)
df_mean.sort_values(ascending=True).head(1) #53th is wort joke

-7.52.1   -3.071944
dtype: float64